name: Deploy Extension to Stores

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install web-ext
        run: npm install -g web-ext
      - name: Create ZIP artifact
        run: web-ext build --source-dir ulaval-helper

      - name: Publish to Firefox Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: cours-filter@exemple.tld
          xpi-path: ./web-ext-artifacts/ulaval_helper-*.zip
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
          channel: listed
      
      - name: Publish to Chrome Web Store
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip-path: ./web-ext-artifacts/ulaval_helper-*.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          upload-only: false
