name: Deploy Extension to Stores

on:
  release:
    types: [published]
  workflow_dispatch:
      inputs:
        reason:
          description: 'Raison du déclenchement manuel'
          required: false
          default: 'Test de CI/CD'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and Install web-ext
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g web-ext

      - name: Update manifest.json Version
        if: github.event_name == 'release'
        run: |
          RELEASE_VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          MANIFEST_PATH="./ulaval-helper/manifest.json"
          
          if [ -z "$RELEASE_VERSION" ]; then
            echo "Pas de tag de release trouvé. La version du manifest ne sera pas modifiée."
          else
            echo "Mise à jour de la version du manifest à $RELEASE_VERSION"
            sudo apt-get install jq -y
            
            jq --arg version "$RELEASE_VERSION" '.version = $version' $MANIFEST_PATH > temp.json
            mv temp.json $MANIFEST_PATH
            
            echo "Version mise à jour avec succès dans $MANIFEST_PATH"
          fi

      - name: Create ZIP artifact
        run: |
          web-ext build --source-dir . 
          
      - name: Publish to Firefox Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: cours-filter@exemple.tld
          xpi-path: web-ext-artifacts/ulaval_helper-*.zip
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
          channel: listed
      
      - name: Publish to Chrome Web Store
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip-path: web-ext-artifacts/ulaval_helper-*.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          upload-only: false